spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/daangn;
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate.hbm2ddl.auto: update
#      ddl-auto: update #애플리케이션 실행 시점에 테이블을 재생성
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug #hibernate가 생성하는 로그가 보여!
    org.hibernate.type: trace

server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800
